### ISSUE TITLE
Rename "section" to "block" and "step" to "task" like Ansible

### ISSUE THREAD

**Issue by ke4roh** [ke4roh/vertx-engine#36]
Not sure if this is necessary, but documenting it here so we can have a discussion about it.

**Comment by LightGuard** [comment]
I think if we're going for the "this behaves like ansible, so it should be easy to understand" then yes, though we do differ quite a bit already and the execution model isn't the same. Really not sure if it's necessary.

**Comment by LightGuard** [comment]
Still on the fence about this.

**Comment by ke4roh** [comment]
I don't think it matters.
