### ISSUE TITLE
One HttpClient

### ISSUE THREAD

**Issue by ke4roh** [ke4roh/vertx-engine#73]
Inner classes with different behavior for different methods can provide a body or not and avoid branching.

**Comment by LightGuard** [comment]
Going to say no on this one. I don’t think it’sa good idea long term

**Comment by ke4roh** [comment]
The odd part here is that then the Solr client is split among multiple implementations for indexing and querying different ways.

**Comment by LightGuard** [comment]
I don’t see that as a problem. Of course there isn’ta reason you can’t do your own subclass that does both.
